---

version: '2'
services:

  rundeck:
    restart: always
    build: .
    command: ./opt/entrypoint.sh
    ports:
      - 4440:4440
    environment:
      - SERVER_URL=http://localhost:4440
      - DATABASE_URL=jdbc:mysql://mysql:3306/rundeck?autoReconnect=true
      - RUNDECK_PASSWORD=lite-nard-guardian-woke-pageboy
      #- LOGIN_MODULE=ldap
      #- JAAS_CONF=/opt/rundeck-properties/jaas-ldap.conf
    links:
      - mysql
    volumes:
      - ./data/projects:/var/rundeck/projects:rw
      - ./data/keys:/var/lib/rundeck_ssh:ro
      - ./prerequisites/opt:/opt
  mysql:
    restart: always
    image: mariadb:latest
    command: mysqld --innodb-buffer-pool-size=20M
    environment:
      - MYSQL_ROOT_PASSWORD=minatory-unbosom-dance-ravel-buddhism
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=lite-nard-guardian-woke-pageboy
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    expose:
      - 3306
